export const problems=[
"Gelecek Kaygısı",
"Dolar",
"Enflasyon",
"KPSS",
"YKS",
"Biz sizi ararız",
"Mobbing",
"N yıl tecrübe lazım",
"Mahalle Baskısı",
"Kadın cinayetleri",
"Cyberbullying",
"Ailevi Beklentiler",
"Daha İş bulmadın mı?",
"Daha Evlenmedin mi ?",
"Çocuk düşünmüyor musunuz?",
"ÖTV-KDV-araç piyasası",
"Bekara-Öğrenciye ev yok",
"Şimdi mezun olunca ne olucan?",
"Öğrenim kredisi",
"Çıkar telefonunu",
"Kalitesiz eğitim",
"Kira-elektrik-doğalgaz",
"Referansınız kim",
"Ekşi sözlük",
"Facebook dayıları",
"Akraba terör örgütü",,
"Psikolog Ücretleri",
"Parasızlık",
"Drill Rap",
"Norm Ender",
"Demet Akalın",
"İbrahim Tatlıses",
"Esra Erol",
"hak-hukuk-gag-guk",
"Duyar Kasmaca Terör Örgütü",
"X Elden gidiyeh",
"Bir zamanlar tüp kuyruğu vardı yiğenim",
"Senin yaşın kaç yeğenim",
"Hard Kapitalizm",
"Küresel Sıcaklık",
"Enes Batur",
"Recep İvedik",
"Cumali Ceber",
"Esra Erol",
"Sigaraya Zam",
"Benzine Zam",
];
